### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by jaredchesebro** [marsvogel/statamic-mailto#2]
Add ability to use a global variable to set email address.

**Comment by marsvogel** [comment]
Sorry for not responding, didn't catch any mail from github. Can you give me an example on how you want it to behave?

**Comment by jaredchesebro** [comment]
I was thinking it could behave similar to this addon: https://statamic.com/marketplace/addons/tel

For example being able to use a tag like this: 
`{{ email_address | mailto }} `
where email_address is a simple text field

Output would be `<a href="mailto:email@example.com">email@example.com</a>`

Of course you could always convert it to a fieldtype.

**Comment by marsvogel** [comment]
Ah okay, I get it now. Give me a couple of days to add this feature. I let you know if I'm done.

**Comment by marsvogel** [comment]
Actually I took the the time _today_ and [released version 2](https://statamic.com/marketplace/addons/mailto) of this addon 🎉

Now you can use a modifier:

**YAML**
```
contact: "mail@example.com"
```
**Template**
```antlers
<!-- shorthand syntax: -->
{{ contact | mailto_link }}
```
**Output**
```html
<a href="mailto:mail@example.com">mail@example.com</a>
```

If you want to, you can use an array:

**YAML**
```yaml
contact:
  email: "Jane Bacon <one@example.com>"
  cc: "John Bacon <two@example.com>"
  bcc: "Eliah Bacon <three@example.com>"
  subject: "Interest in Bacon"
  body: "Don't forget to add your contact informations :)"
  display: "Get in Touch"
```
**Template**
```antlers
<!-- shorthand syntax: -->
{{ contact | mailto_link }}
```
**Output**
```html
<a href="mailto:Jane Bacon <one@example.com>?cc=John Bacon <two@example.com>&bcc=Eliah Bacon <three@example.com>&subject=Interest in Bacon&body=Don't forget to add your contact informations :)">Get in Touch</a>
```

Except the real new stuff, there are a couple of breaking changes:

* The tag `mailto` is renamed to `mailto_link` to avoid name collisions
* The shorthand syntax wont take email strings anymore

```
<!-- this won't work anymore -->
{{ mailto_link:mail@example.com }}
```

I'm closing this issue. Feel free to open a new one, if you experience any strange behaviour.

Thanks for using my plugin!
